use alloc::{rc::Rc, string::String};
use core::fmt::{self, Display, Formatter};

#[derive(Clone, Eq, PartialEq, PartialOrd, Ord, Hash, Debug)]
pub enum Token {
    Identifier(Rc<String>),
    Constant(i32),
    Keyword(Keyword),
    OpenParenthesis,
    CloseParenthesis,
    OpenBrace,
    CloseBrace,
    Semicolon,
    Tilde,
    Hyphen,
    PlusSign,
    Asterisk,
    Slash,
    Percent,
    Ampersand,
    Bar,
    Circumflex,
    TwoLessThanOps,
    TwoGreaterThanOps,
    ExclamationPoint,
    TwoAmpersands,
    TwoBars,
    TwoEqualSigns,
    NotEqualSign,
    LessThanOp,
    GreaterThanOp,
    LessThanOrEqualToOp,
    GreaterThanOrEqualToOp,
    EqualSign,
    PlusEqualSign,
    HyphenEqualSign,
    AsteriskEqualSign,
    SlashEqualSign,
    PercentEqualSign,
    AmpersandEqualSign,
    BarEqualSign,
    CircumflexEqualSign,
    TwoLessThanOpsEqualSign,
    TwoGreaterThanOpsEqualSign,
    TwoPlusSigns,
    TwoHyphens,
    QuestionMark,
    Colon,
    Comma,
}

#[derive(Copy, Clone, Eq, PartialEq, PartialOrd, Ord, Hash, Debug)]
pub enum Keyword {
    Int,
    Void,
    Return,
    If,
    Else,
    Do,
    While,
    For,
    Break,
    Continue,
    Extern,
    Const,
    Switch,
    Case,
    Default,
}

impl Display for Token {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        match self {
            Token::Identifier(identifier) => write!(f, "{identifier}"),
            Token::Constant(value) => write!(f, "{value}"),
            Token::Keyword(keyword) => write!(f, "{keyword}"),
            Token::OpenParenthesis => write!(f, "("),
            Token::CloseParenthesis => write!(f, ")"),
            Token::OpenBrace => write!(f, "{{"),
            Token::CloseBrace => write!(f, "}}"),
            Token::Semicolon => write!(f, ";"),
            Token::Tilde => write!(f, "~"),
            Token::Hyphen => write!(f, "-"),
            Token::PlusSign => write!(f, "+"),
            Token::Asterisk => write!(f, "*"),
            Token::Slash => write!(f, "/"),
            Token::Percent => write!(f, "%"),
            Token::Ampersand => write!(f, "&"),
            Token::Bar => write!(f, "|"),
            Token::Circumflex => write!(f, "^"),
            Token::TwoLessThanOps => write!(f, "<<"),
            Token::TwoGreaterThanOps => write!(f, ">>"),
            Token::ExclamationPoint => write!(f, ""),
            Token::TwoAmpersands => write!(f, "&&"),
            Token::TwoBars => write!(f, "||"),
            Token::TwoEqualSigns => write!(f, "=="),
            Token::NotEqualSign => write!(f, "!="),
            Token::LessThanOp => write!(f, "<"),
            Token::GreaterThanOp => write!(f, ">"),
            Token::LessThanOrEqualToOp => write!(f, "<="),
            Token::GreaterThanOrEqualToOp => write!(f, ">="),
            Token::EqualSign => write!(f, "="),
            Token::PlusEqualSign => write!(f, "+="),
            Token::HyphenEqualSign => write!(f, "-="),
            Token::AsteriskEqualSign => write!(f, "*="),
            Token::SlashEqualSign => write!(f, "/="),
            Token::PercentEqualSign => write!(f, "%="),
            Token::AmpersandEqualSign => write!(f, "&="),
            Token::BarEqualSign => write!(f, "|="),
            Token::CircumflexEqualSign => write!(f, "^="),
            Token::TwoLessThanOpsEqualSign => write!(f, "<<="),
            Token::TwoGreaterThanOpsEqualSign => write!(f, ">>="),
            Token::TwoPlusSigns => write!(f, "++"),
            Token::TwoHyphens => write!(f, "--"),
            Token::QuestionMark => write!(f, "?"),
            Token::Colon => write!(f, ":"),
            Token::Comma => write!(f, ","),
        }
    }
}

impl Display for Keyword {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        match self {
            Keyword::Int => write!(f, "int"),
            Keyword::Void => write!(f, "void"),
            Keyword::Return => write!(f, "return"),
            Keyword::If => write!(f, "if"),
            Keyword::Else => write!(f, "else"),
            Keyword::Do => write!(f, "do"),
            Keyword::While => write!(f, "while"),
            Keyword::For => write!(f, "for"),
            Keyword::Break => write!(f, "break"),
            Keyword::Continue => write!(f, "continue"),
            Keyword::Extern => write!(f, "extern"),
            Keyword::Const => write!(f, "const"),
            Keyword::Switch => write!(f, "switch"),
            Keyword::Case => write!(f, "case"),
            Keyword::Default => write!(f, "default"),
        }
    }
}
